//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// iMaster.rc에서 사용되고 있습니다.
//
#define IDR_MAINFRAME                   99
#define IDD_ABOUTBOX                    100
#define IDD_JOBINFO_FORM                101
#define IDD_EDIT_RESIZE                 102
#define IDB_BITMAP3                     102
#define IDB_SMALL_FEATURE               102
#define IDD_PROGRESS_DLG                103
#define IDD_EDIT_MOVE                   104
#define IDD_CAMINFO_FORM                105
#define IDD_EDIT_DELETE                 106
#define IDD_SETTINGS_DLG                107
#define IDD_DISPLAY_FORM                108
#define IDD_EXTRACT_DLG                 109
#define IDD_PROCESS_DLG                 110
#define IDD_HISTOGRAM                   111
#define IDD_EDIT_SYMBOL_SELECT          112
#define IDD_EDIT_ADD                    113
#define IDD_EDIT_COPY                   114
#define IDD_EDIT_ADD_SUB_PAD            115
#define IDD_EDIT_ADD_SUB_LINE           116
#define IDD_EDIT_MAKE_SYMBOL            117
#define IDD_EDIT_SELECT_ATTRIBUTE       118
#define IDD_EDIT_SELECT_SYMBOL          119
#define IDD_DIALOG1                     120
#define IDD_MEASURE_INFO_V2             120
#define IDD_DIALOG_ALIGN_MASK           121
#define IDD_MINIMAP_FORM                122
#define IDD_DIALOG_SAVE_AS              123
#define IDD_STATUS_DLG                  124
#define IDB_SMALL_ADD_FEATURE           124
#define IDD_MINIMAP_FORM_V2             125
#define IDD_EDIT_ADD_SUB_ARC            126
#define IDD_EDIT_ADD_SUB_SURFACE        127
#define IDD_EDIT_ROTATE                 128
#define IDD_EDIT_ADD_SUB_TP             129
#define IDD_EIDT_FEATURE                130
#define IDD_EDIT_FEATURE                131
#define IDS_RIB_CAM_MASTER_EN           199
#define IDS_RIB_CAM_MASTER_KR           200
#define IDS_RIB_VIEW_CATEGORY           201
#define IDS_RIB_HOME                    202
#define IDS_RIB_REFRESH                 203
#define IDS_RIB_SETTING                 204
#define IDS_RIB_MODE                    205
#define IDS_RIB_LINESCAN                206
#define IDS_RIB_AREASCAN                207
#define IDS_RIB_PANEL                   208
#define IDS_RIB_LOAD_LAYER              209
#define IDS_RIB_PROCESS                 210
#define IDS_RIB_MAKE_MASTER             211
#define IDS_RIB_TRANSFER_MASTER         212
#define IDS_RIB_VIEW_FORMS              213
#define IDS_RIB_VIEW_JOB_INFO           214
#define IDS_RIB_VIEW_CAM_INFO           215
#define IDS_RIB_VIEW_LAYER_INFO         216
#define IDS_RIB_VIEW_LOG                217
#define IDS_RIB_DISPLAY                 218
#define IDS_RIB_FOV_VIEW                219
#define IDS_STATUS_PANE1                220
#define IDS_STATUS_PANE2                221
#define IDS_TOOLBAR_STANDARD            222
#define IDS_TOOLBAR_CUSTOMIZE           223
#define IDS_RIB_CELL_AREA               224
#define IDS_RIB_STEP_REPEAT             225
#define IDS_RIB_PROFILE_VIEW            226
#define IDS_RIB_SURFACE_VIEW            227
#define IDS_RIB_WORK_DIRECTION          228
#define IDS_RIB_MIRROR_H                229
#define IDS_RIB_ROTATION90              230
#define IDS_RIB_ROTATION360             231
#define IDS_RIB_ROTATION180             232
#define IDS_RIB_ROTATION270             233
#define IDS_RIB_FOV_EDIT                234
#define IDS_RIB_FOV_HSCAN               235
#define IDS_RIB_FOV_HJIGJAG             236
#define IDS_RIB_FOV_VSCAN               237
#define IDS_RIB_FOV_VJIGJAG             238
#define IDS_RIB_VERSION                 239
#define IDS_RIB_INFO                    240
#define IDS_RIB_RULER                   241
#define IDS_FILE_VIEW                   242
#define IDS_CLASS_VIEW                  243
#define IDS_OUTPUT_WND                  244
#define IDS_PROPERTIES_WND              245
#define IDS_RIB_NSIS                    246
#define IDS_RIB_SIDE                    247
#define IDS_RIBBON_FRONT                248
#define IDS_RIBBON_BACK                 249
#define IDS_RIB_VIEW_MEASURE_INFO       250
#define IDS_RIB_BOUNDARY_VIEW           251
#define IDS_RIB_MIRROR_V                252
#define IDS_RIB_MAKE_ALIGN              253
#define IDS_RIB_VIEW_MINIMAP_VIEW       254
#define IDS_RIB_SET_ALIGN               255
#define IDS_RIB_SET_MEASURE_NSIS        256
#define IDS_RIB_SET_MEASURE_SR          257
#define IDS_RIB_PRESR                   258
#define IDS_RIB_POSTSR                  259
#define IDS_RIB_SET_ALIGN_PANEL         260
#define IDS_RIB_SET_ALIGN_STRIP         261
#define IDS_RIB_SET_ALIGN_UNIT          262
#define IDS_RIB_GROUP_SAVE              263
#define IDS_RIB_SAVE                    264
#define IDS_RIB_SAVE_AS                 265
#define IDS_RIB_RECIPE                  266
#define IDS_RIB_MANUFACTURE             267
#define IDS_RIB_SET_MEASURE_NSIS_PANEL  268
#define IDS_RIB_SET_MEASURE_NSIS_STRIP  269
#define IDS_RIB_SET_MEASURE_NSIS_UNIT   270
#define IDS_RIB_SET_MEASURE_SR_PANEL    271
#define IDS_RIB_SET_MEASURE_SR_STRIP    272
#define IDS_RIB_SET_MEASURE_SR_UNIT     273
#define IDS_BUILD_TAB                   274
#define IDS_DEBUG_TAB                   275
#define IDS_FIND_TAB                    276
#define IDS_EXPLORER                    277
#define IDS_EDIT_MENU                   278
#define IDS_RIB_EDIT_COPY               279
#define IDS_RIB_EDIT_CATEGORY           280
#define IDS_RIB_EDIT_SUBJECT            281
#define IDS_RIB_EDIT_EDITMODE           282
#define IDS_RIB_EDIT_RESIZE             283
#define IDS_RIB_EDIT_MOVE               284
#define IDS_RIB_EDIT_DELETE             285
#define IDS_RIB_EDIT_ADD                286
#define IDS_RIB_EDIT_ROTATE             287
#define IDS_RIB_EDIT_MASK               288
#define IDS_RIB_EDIT_TEST_SAVE          289
#define IDS_RIB_PREVIEW                 290
#define IDS_RIB_VIEW_ALIGN              291
#define IDS_RIB_VIEW_MASK               292
#define IDS_RIB_EDIT_FEATURE            293
#define IDS_RIB_SET_MONITOR             294
#define IDS_RIB_ADD_LINE                295
#define IDS_RIB_ADD_CIRCLE              296
#define IDS_RIB_ADD_SQUARE              297
#define IDS_RIB_ADD_RECT                298
#define IDS_RIB_ADD_RECTXR              299
#define IDS_RIB_ADD_RECTXC              300
#define IDS_RIB_ADD_OVAL                301
#define IDS_RIB_ADD_DIAMOND             302
#define IDS_RIB_ADD_OCTAGON             303
#define IDS_RIB_ADD_ROUND_DONUT         304
#define IDS_RIB_ADD_SQUARE_DONUT        305
#define IDS_RIB_ADD_HORIZONTAL_HEXAGON  306
#define IDS_RIB_ADD_VETICAL_HEXAGON     307
#define IDS_RIB_ADD_BUTTERFLY           308
#define IDS_RIB_ADD_SQUARE_BUTTERFLY    309
#define IDS_RIB_ADD_TRIANGLE            310
#define IDS_RIB_ADD_HALF_OVAL           311
#define IDS_RIB_ADD_ROUND_THERMAL_ROUNDED 312
#define IDS_RIB_ADD_ROUND_THERMAL_SQUARED 313
#define IDS_RIB_ADD_SQUARE_THERMAL      314
#define IDS_RIB_ADD_SQUARE_THERMAL_OPEN_CORNERS 315
#define IDS_RIB_ADD_SQUARE_ROUND_THERMAL 316
#define IDS_RIB_ADD_RECTANGULAR_THERMAL 317
#define IDS_RIB_ADD_RECTANGULAR_THERMAL_OPEN_CORNERS 318
#define IDS_RIB_ADD_ELLIPSE             319
#define IDS_RIB_ADD_MOIRE               320
#define IDS_RIB_ADD_HOLE                321
#define IDS_RIB_ADD_ARC                 322
#define IDS_RIB_ADD_CROSS               323
#define IDS_RIB_ADD_SURFACE             324
#define IDS_RIB_ADD_SUBJECT             325
#define IDS_RIB_ADD_LINE_X              326
#define IDS_RIB_ADD_LINE_Y              327
#define IDS_RIB_LAYER_COMBOBOX          328
#define IDS_RIB_ADD_LINE_X_FEATURE      329
#define IDS_RIB_ADD_LINE_Y_FEATURE      330
#define IDS_RIB_SET_ALIGNAUTO           360
#define IDS_RIB_SET_ALIGNMANUAL         361
#define IDS_RIB_ADD_CIRCLE_AUTO         370
#define IDS_RIB_ADD_RECT_AUTO           371
#define IDS_RIB_ADD_CROSS_AUTO          372
#define IDI_FILE_VIEW                   400
#define IDI_FILE_VIEW_HC                401
#define IDI_CLASS_VIEW                  402
#define IDI_CLASS_VIEW_HC               403
#define IDI_OUTPUT_WND                  404
#define IDI_OUTPUT_WND_HC               405
#define IDI_PROPERTIES_WND              406
#define IDI_PROPERTIES_WND_HC           407
#define IDI_REFRESH_ICON                408
#define IDI_SETTING_ICON                409
#define IDI_LINESCAN_ICON               410
#define IDI_AREASCAN_ICON               411
#define IDI_PANEL_ICON                  412
#define IDI_LOAD_LAYER_ICON             413
#define IDI_MAKE_MASTER_ICON            414
#define IDI_TRANSFER_MASTER_ICON        415
#define IDI_VIEW_JOB_ICON               416
#define IDI_VIEW_CAM_ICON               417
#define IDI_VIEW_LAYER_ICON             418
#define IDI_VIEW_LOG_ICON               419
#define IDI_FOV_VIEW_ICON               420
#define IDI_CELL_AREA_ICON              421
#define IDI_PROFILE_VIEW_ICON           422
#define IDI_SURFACE_VIEW_ICON           423
#define IDI_STEP_REPEAT_ICON            424
#define IDI_MIRROR_H_ICON               425
#define IDI_ROTATION90_ICON             426
#define IDI_ROTATION180_ICON            427
#define IDI_ROTATION270_ICON            428
#define IDI_ROTATION360_ICON            429
#define IDI_HSCAN_ICON                  430
#define IDI_VSCAN_ICON                  431
#define IDI_HJIGJAG_ICON                432
#define IDI_VJIGJAG_ICON                433
#define IDI_VERSION_ICON                434
#define IDI_RULER_ICON                  435
#define IDI_FRONTSIDE_ICON              436
#define IDI_BACKSIDE_ICON               437
#define IDI_VIEW_MEASURE_ICON           438
#define IDI_EDIT_MODE                   439
#define IDI_EDIT_ADD                    440
#define IDI_EDIT_DELETE                 441
#define IDI_EDIT_MOVE                   442
#define IDI_EDIT_RESIZE                 443
#define IDI_SHOW_BOUNDARY               444
#define IDI_MIRROR_V_ICON               445
#define IDI_ALIGN_RGN_ICON              446
#define IDI_MASK_RGN_ICON               447
#define IDI_DRAW_RGN_ICON               448
#define IDI_UNIT_RGN_ICON               449
#define IDI_STRIP_RGN_ICON              450
#define IDI_PANEL_RGN_ICON              451
#define IDI_PREVIEW_ICON                452
#define IDI_CELL_DATA                   453
#define IDI_MINIMAP_ICON                454
#define IDI_ICON_SAVE_AS                456
#define IDI_ICON_SAVE                   457
#define IDI_ALIGN_ICON                  458
#define IDI_DEPTH_ICON                  459
#define IDI_THICKNESS_ICON              460
#define IDI_POSTSR_ICON                 461
#define IDI_PRESR_ICON                  462
#define IDI_EMPTY_ICON                  463
#define IDB_MAIN                        500
#define IDB_TREEBTNS                    501
#define IDB_EXPLORER_24                 502
#define IDB_SORT_24                     503
#define IDB_FILE_VIEW                   504
#define IDB_FILE_VIEW_24                505
#define IDB_CLASS_VIEW                  506
#define IDB_CLASS_VIEW_24               507
#define IDB_MENU_IMAGES_24              508
#define IDB_PROPERTIES_HC               509
#define IDB_DIAMOND                     510
#define IDB_ELLIPSE                     511
#define IDB_HALF_OVAL                   512
#define IDB_HORIZONTAL_HEXAGON          513
#define IDB_MOIRE                       514
#define IDB_OCTAGON                     515
#define IDB_VERTICAL_HEXAGON            516
#define IDB_ROUND_DONUT                 517
#define IDB_SQUARE_BUTTERFLY            518
#define IDB_SQUARE_DONUT                519
#define IDB_SQAURE_THERMAL_OPEN_CORNERS 520
#define IDB_RIB_EDIT_STEP               521
#define IDB_RIB_EDIT_UNIT               522
#define IDB_SQUARE_ROUND_THERMAL        523
#define IDB_RIB_EDIT_STRIP              524
#define IDB_TRIANGLE                    525
#define IDB_RIB_EDIT_PANEL              526
#define IDB_VERTICALHEXAGON             527
#define IDB_BITMAP1                     528
#define IDB_CIRCLE                      529
#define IDB_SQUARE                      530
#define IDB_RECT                        531
#define IDB_OVAL                        532
#define IDB_HOLE                        533
#define IDB_BUTTERFLY                   534
#define IDB_RECTANGLULAR_THERMAL        535
#define IDB_RECTANGLUAR_THERMAL_OPEN_CORNERS 536
#define IDB_ROUND_THERMAL_SQUARED       537
#define IDB_ROUND_THERMAL_ROUNDED       538
#define IDB_BITMAP2                     539
#define IDB_SQUARETHERMAL               540
#define IDB_CHAMFEREDRECT               541
#define IDB_ROUNDEDRECT                 542
#define IDD_EDIT_DLG                    543
#define IDD_DIALOG_ALIGN_MASK2          544
#define IDD_DIALOG_ALIGN_MASK3          545
#define ID_VIEW_CLASSVIEW               600
#define ID_VIEW_FILEVIEW                601
#define ID_PROPERTIES                   602
#define ID_OPEN                         603
#define ID_OPEN_WITH                    604
#define ID_DUMMY_COMPILE                605
#define ID_CLASS_ADD_MEMBER_FUNCTION    606
#define ID_CLASS_ADD_MEMBER_VARIABLE    607
#define ID_CLASS_DEFINITION             608
#define ID_CLASS_PROPERTIES             609
#define ID_NEW_FOLDER                   610
#define ID_SORT_MENU                    611
#define ID_WINDOW_MANAGER               612
#define ID_SORTING_GROUPBYTYPE          613
#define ID_SORTING_SORTALPHABETIC       614
#define ID_SORTING_SORTBYTYPE           615
#define ID_SORTING_SORTBYACCESS         616
#define ID_VIEW_OUTPUTWND               617
#define ID_VIEW_PROPERTIESWND           618
#define ID_SORTPROPERTIES               619
#define ID_PROPERTIES1                  620
#define ID_PROPERTIES2                  621
#define ID_EXPAND_ALL                   622
#define ID_STATUSBAR_PANE1              623
#define ID_STATUSBAR_PANE2              624
#define ID_VIEW_CUSTOMIZE               625
#define ID_TOOLS_MACRO                  626
#define ID_LOG_LISTBOX                  627
#define ID_GENERALINFO_DOCPANE          628
#define ID_SET_STYLE                    629
#define ID_VIEW_APPLOOK_WIN_2000        630
#define ID_VIEW_APPLOOK_OFF_XP          631
#define ID_VIEW_APPLOOK_WIN_XP          632
#define ID_VIEW_APPLOOK_OFF_2003        633
#define ID_VIEW_APPLOOK_VS_2005         634
#define ID_VIEW_APPLOOK_VS_2008         635
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   636
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  637
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 638
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   639
#define ID_VIEW_APPLOOK_WINDOWS_7       640
#define ID_LAYER_INFO_DOCPANE           641
#define IDP_SOCKETS_INIT_FAILED         650
#define IDP_OLE_INIT_FAILED             651
#define IDR_iMasterTYPE                 661
#define IDR_POPUP_EDIT                  662
#define IDR_MAINFRAME_256               664
#define IDR_SORT                        665
#define IDR_EXPLORER                    666
#define IDR_POPUP_SORT                  667
#define IDR_POPUP_EXPLORER              668
#define IDR_MENU_IMAGES                 669
#define IDR_OUTPUT_POPUP                670
#define IDR_PROPERTIES                  671
#define IDR_THEME_MENU                  674
#define IDR_POPUP_HISTOGRAM             675
#define ID_OBJECT_STYLES                676
#define ID_MEATURE_INFO_DOCPANE         676
#define ID_MEATURE_INFO_V2_DOCPANE      677
#define ID_MINIMAP_FORM_V2              678
#define IDC_STC_SELECTJOB               1000
#define IDC_TREE_FILE                   1001
#define IDC_STC_LOGO                    1002
#define IDC_STC_ROUNDPROGRESS           1003
#define IDC_LIST_STEP                   1005
#define IDC_LIST_LAYER                  1006
#define IDC_STATIC_PICTURE              1007
#define IDC_LIST_COMP                   1008
#define IDC_STATIC_TITLE                1009
#define IDC_STATIC_MODELNAME            1010
#define IDC_STATIC_MODELNAME_TXT        1011
#define IDC_STATIC_WORKSTEP             1012
#define IDC_STATIC_WORKSTEP_TXT         1013
#define IDC_STATIC_PATTERN_LAYER        1014
#define IDC_STATIC_PATTERN_LAYER_TXT    1015
#define IDC_STATIC_DRILL_LAYER          1016
#define IDC_STATIC_DRILL_LAYER_TXT      1017
#define IDC_STATIC_DRILL_LAYER2         1018
#define IDC_STATIC_SUB_TITLE            1019
#define IDC_STATIC_DRILL_LAYER3         1020
#define IDC_STATIC_SUB_TITLE2           1021
#define IDC_STATIC_DRILL_LAYER4         1022
#define IDC_EXTRACT_PROGRESS_BAR        1023
#define IDC_STATIC_                     1024
#define IDC_STATIC_WORKLAYER            1025
#define IDC_STATIC_DRILL_LAYER5         1026
#define IDC_STATIC_VIA_LAYER            1027
#define IDC_STATIC_RESOLUTION           1028
#define IDC_STATIC_VIA_LAYER_TXT        1029
#define IDC_STATIC_WORKLAYER_TXT        1030
#define IDC_STATIC_RESOLUTION_TXT       1031
#define IDC_MAKEMASTER_PROGRESS_BAR     1032
#define IDC_BUTTON_SHOW                 1033
#define IDC_BUTTON_SELECT               1034
#define IDC_BUTTON_UNSELECT             1035
#define IDC_BUTTON_HIDE                 1036
#define IDC_STATIC_HISTOGRAM            1037
#define IDC_STATIC_LAYERNAME            1038
#define IDC_STATIC_STEPNAME             1039
#define IDC_BUTTON_ALL_SHOW             1040
#define IDC_BUTTON_RESET_SELECT         1041
#define IDC_BUTTON_CANCEL               1042
#define IDC_BUTTON_ALL_SHOW2            1043
#define IDC_BUTTON_CLOSE                1044
#define IDC_BUTTON_MOVE_AXIS_Y          1047
#define IDC_BUTTON_APPLY                1048
#define IDC_RADIO_KEEP_CORNER_YES       1049
#define IDC_BUTTON_SELECT_ONLY          1050
#define IDC_BUTTON_SETDATA              1051
#define IDC_BUTTON_MOVE_AXIS_X          1052
#define IDC_BUTTON_PREVIEW              1053
#define IDC_BUTTON_MOVE_AXIS_XY         1054
#define IDC_RADIO_KEEP_CORNER_NO        1055
#define IDC_EDIT_FACTOR                 1056
#define IDC_STATIC_RESIZE_UNIT          1057
#define IDC_EDIT_PITCH_Y                1058
#define IDC_EDIT_FACTOR_HEIGHT          1059
#define IDC_STATIC_RESIZE_UNIT2         1060
#define IDC_EDIT_REPEAT_X               1061
#define IDC_EDIT_REPEAT                 1062
#define IDC_STATIC_RESIZE_UNIT3         1063
#define IDC_RADIO_MOVE_X                1064
#define IDC_EDIT_REPEAT_Y               1065
#define IDC_RADIO_MOVE_Y                1066
#define IDC_BUTTON_ALL_FEATURE          1067
#define IDC_STATIC_RESIZE_UNIT4         1068
#define IDC_RADIO_MOVE_XY               1069
#define IDC_EDIT_REPEAT_                1070
#define IDC_STATIC_RESIZE_UNIT5         1071
#define IDC_EDIT_COPY_Y                 1072
#define IDC_STATIC_RESIZE_UNIT6         1073
#define IDC_EDIT_PITCH_X                1075
#define IDC_RADIO_POLARITY_POS          1076
#define IDC_EDIT_COPY_X                 1077
#define IDC_RADIO_POLARITY_NEG          1078
#define IDC_EDIT_SHAPE                  1079
#define IDC_BUTTON_MAKE_SHAPE           1080
#define IDC_EDIT_ATTRIBUTE              1081
#define IDC_COMBO_LAYER                 1082
#define IDC_RADIO_MIRROR_NO             1083
#define IDC_RADIO_MIRROR_YES            1084
#define IDC_EDIT_CENTER_POS_X           1085
#define IDC_EDIT_CENTER_POS_Y           1086
#define IDC_BUTTON_SELECT_ATTRIBUTE     1087
#define IDC_EDIT_END_POS_X              1088
#define IDC_EDIT_ADD_POINT_X            1089
#define IDC_EDIT_ADD_POINT_Y            1090
#define IDC_RADIO_ANGLE_0               1091
#define IDC_RADIO_ANGLE_90              1092
#define IDC_RADIO_ANGLE_180             1093
#define IDC_RADIO_ANGLE_270             1094
#define IDC_EDIT_END_POINT_X            1095
#define IDC_BUTTON_SELECT_POS           1096
#define IDC_EDIT_POINT_X                1097
#define IDC_EDIT_END_POS_Y              1098
#define IDC_BUTTON_SELECT_ADD_POINT     1099
#define IDC_EDIT_START_POS_X            1100
#define IDC_BUTTON_SELECT_CENTER_POINT  1101
#define IDC_EDIT_START_POS_Y            1102
#define IDC_EDIT_END_POINT_Y            1103
#define IDC_BUTTON_SELECT_END_POS       1104
#define IDC_BUTTON_SELECT_END_POINT     1105
#define IDC_LIST_PARAM                  1106
#define IDC_BUTTON_SELECT_CENTER_POS    1107
#define IDC_EDIT_POINT_Y                1108
#define IDC_SHAPE_DATA                  1109
#define IDC_TABLE_ATTRIBUTE_STRING      1110
#define IDC_BUTTON_SELECT_SYMBOL        1111
#define IDC_RADIO_SHAPE_LINE            1120
#define IDC_RADIO_SHAPE_PAD             1121
#define IDC_RADIO_SHAPE_ARC             1122
#define IDC_RADIO_SHAPE_SURFACE         1123
#define IDC_RADIO_SHAPE_TP              1124
#define IDC_RADIO_SHAPE_RESERVE4        1125
#define IDC_RADIO_SHAPE_RESERVE5        1126
#define IDC_RADIO_SHAPE_RESERVE6        1127
#define IDC_RADIO_SHAPE_RESERVE7        1128
#define IDC_RADIO_SHAPE_RESERVE8        1129
#define IDC_RADIO_SYMBOL_CIRCLE         1130
#define IDC_RADIO_SYMBOL_SQUARE         1131
#define IDC_RADIO_SYMBOL_RECT           1132
#define IDC_RADIO_SYMBOL_ROUNDED_RECT   1133
#define IDC_RADIO_SYMBOL_CHAMFERED_RECT 1134
#define IDC_RADIO_SYMBOL_OVAL           1135
#define IDC_RADIO_SYMBOL_DIAMOND        1136
#define IDC_RADIO_SYMBOL_OCTAGON        1137
#define IDC_RADIO_SYMBOL_ROUND_DONUT    1138
#define IDC_RADIO_SYMBOL_SQUARE_DONUT   1139
#define IDC_RADIO_SYMBOL_HORIZONTAL_HEXAGON 1140
#define IDC_RADIO_SYMBOL_VERTICAL_HEXAGON 1141
#define IDC_RADIO_SYMBOL_BUTTERFLY      1142
#define IDC_RADIO_SYMBOL_SQUARE_BUTTERFLY 1143
#define IDC_RADIO_SYMBOL_TRIANGLE       1144
#define IDC_RADIO_SYMBOL_HALF_OVAL      1145
#define IDC_RADIO_SYMBOL_ROUND_THERMAL_ROUNDED 1146
#define IDC_RADIO_SYMBOL_ROUND_THERMAL_SQUARED 1147
#define IDC_RADIO_SYMBOL_SQUARE_THERMAL 1148
#define IDC_RADIO_SYMBOL_SQUARE_THERMAL_OPEN_CORNERS 1149
#define IDC_RADIO_SYMBOL_SQUARE_ROUND_THERMAL 1150
#define IDC_RADIO_SYMBOL_RECTANGULAR_THERMAL 1151
#define IDC_RADIO_SYMBOL_RECTANGULAR_THERMAL_OPEN_CORNERS 1152
#define IDC_RADIO_SYMBOL_ELLIPSE        1153
#define IDC_RADIO_SYMBOL_MOIRE          1154
#define IDC_RADIO_SYMBOL_HOLE           1155
#define IDC_RADIO_SYMBOL_RESERVE_27     1156
#define IDC_RADIO_SYMBOL_RESERVE_28     1157
#define IDC_RADIO_SYMBOL_RESERVE_29     1158
#define IDC_RADIO_SYMBOL_NULL           1159
#define IDC_BUTTON_SELECT_START_POS     1200
#define IDC_EDIT_ATTRIBUTE_NAME         1201
#define IDC_BUTTON_ADD_ALIGN_MASK       1201
#define IDC_EDIT_ATTRIBUTE_STRING       1202
#define IDC_BUTTON_RESIZE               1202
#define IDC_RADIO_TABLE_ATTRIBUTE_NAME  1203
#define IDC_BUTTON_DELETE               1203
#define IDC_RADIO_NEW_ATTRIBUTE_NAME    1204
#define IDC_BUTTON_ADD_AUTO_ALIGN       1204
#define IDC_RADIO_TABLE_ATTRIBUTE_STRING 1205
#define IDC_BUTTON_ADD_AUTO_ALIGN2      1205
#define IDC_BUTTON_SAVE_ALIGN_SPEC      1205
#define IDC_RADIO_NEW_ATTRIBUTE_STRING  1206
#define IDC_TABLE_ATTRIBUTE_NAME        1207
#define IDC_TABLE_SYMBOL                1208
#define IDC_BUTTON_MAKE_SYMBOL          1209
#define IDC_EDIT_SYMBOL                 1210
#define IDC_EDIT_MOVEX                  1211
#define IDC_EDIT_MOVEY                  1212
#define IDC_RADIO_TYPE_ALIGN            1213
#define IDC_RADIO_TYPE_MASK             1214
#define IDC_EDIT_FACTOR_WIDTH           1222
#define IDC_BUTTON_AUTO_SEARCH          1223
#define IDC_BUTTON_TEST_CLEAR           1224
#define IDC_STATIC_PANELGRID            1225
#define IDC_STATIC_ALLGRID              1226
#define IDC_STATIC_STRIPGRID            1227
#define IDC_EDIT_JOBNAME                1228
#define IDC_LIST_STATUS                 1233
#define IDC_EDIT5                       1234
#define IDC_EDIT_CURVE_POS_Y            1235
#define IDC_EDIT_CURVE_POS_X            1236
#define IDC_EDIT_START_POINT_X          1237
#define IDC_EDIT_START_POINT_Y          1238
#define IDC_EDIT_CENTER_POINT_X         1239
#define IDC_EDIT_CENTER_POINT_Y         1240
#define IDC_BUTTON_SELECT_START_POINT   1241
#define IDC_RADIO_COPY_ONCE             1242
#define IDC_RADIO_COPY_REPEAT           1243
#define IDC_RADIO_CW                    1244
#define IDC_RADIO_CCW                   1245
#define IDC_BUTTON_END                  1246
#define IDC_BUTTON1                     1301
#define IDC_ICON__CIRCLE                1301
#define IDC_BUTTON_ADD_POSITON          1302
#define IDC_ICON__Square                1302
#define IDC_BUTTON_SELECT_CROSS_CENTER  1303
#define IDC_ICON__Rectangle             1303
#define IDC_CIRCLE_ICON                 1304
#define IDC_ICON__ROUND__RECT           1304
#define IDC_ADD_TP                      1305
#define IDC_ICON__CHAMFERED__RECT       1305
#define IDC_BUTTON_ADD_CROSS            1306
#define IDC_ICON__OVAL                  1306
#define IDC_SYSTEMSPEC_GRID             1307
#define IDC_ICON__DIAMOND               1307
#define IDC_SAVENAPPLY_BTN              1308
#define IDC_ICON__OCTAGON               1308
#define IDC_RESET_BTN                   1309
#define IDC_ICON__ROUND__DONUT          1309
#define IDC_EDIT_CROSS_CENTER_X         1310
#define IDC_ICON__DONUT__S              1310
#define IDC_ICON__HEX__L                1311
#define IDC_ICON__HEX__S                1312
#define IDC_ICON__BFR                   1313
#define IDC_ICON__BFS                   1314
#define IDC_ICON__TRI                   1315
#define IDC_ICON__OVAL_H                1316
#define IDC_ICON__THR                   1317
#define IDC_ICON__THS                   1318
#define IDC_ICON__S__THS                1319
#define IDC_ICON__S__THO                1320
#define IDC_ICON__SR_THS                1321
#define IDC_ICON__RC__THS               1322
#define IDC_ICON__RC__THO               1323
#define IDC_ICON__EL                    1324
#define IDC_ICON__MOIRE                 1325
#define IDC_ICON__HOLE                  1326
#define IDC_PREVIEW_BUTTON              1327
#define IDC_EDIT_GRID                   1328
#define IDC_DELETE_BTN                  1329
#define IDC_CHECK_ADD_ALIGN_MASK_FEATURE_BASE 1450
#define IDC_EDIT1                       1451
#define IDC_ALIGN_PROPERTYGRID          1452
#define IDC_BUTTON_ODB_LOCATION_1       1453
#define IDC_BUTTON_ODB_LOCATION_2       1454
#define IDC_BUTTON_ODB_LOCATION_3       1455
#define IDC_BUTTON_ODB_LOCATION_4       1456
#define ID_HISTOGRAM_FEATURE            32771
#define ID_EDIT_FEATRURE                32772
#define ID_HISTOGRAM_ATTRIBUTE          32773
#define ID_HISTOGRAM_SYMBOL             32774
#define ID_EDIT_APPLY                   32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1455
#define _APS_NEXT_SYMED_VALUE           454
#endif
#endif
