#pragma once

#ifndef __COMMONIF_ERROR_H__
#define __COMMONIF_ERROR_H__

#define RESULT_GOOD						0
#define RESULT_BAD						RESULT_GOOD+1
#define ERROR_NOT_SUPPORT				RESULT_GOOD+2
#define ERROR_FILE_FORMAT				RESULT_GOOD+3
#define ERROR_FILE_EXIST				RESULT_GOOD+4
#define ERROR_LOAD_MATRIX				RESULT_GOOD+5
#define ERROR_LOAD_FONT					RESULT_GOOD+6
#define ERROR_LOAD_STEP					RESULT_GOOD+7
#define ERROR_LOAD_LAYER				RESULT_GOOD+8
#define ERROR_LOAD_SYMBOL				RESULT_GOOD+9
#define ERROR_COPY_FILE					RESULT_GOOD+10
#define ERROR_CREATE_PROCESS			RESULT_GOOD+11

#endif
